### Limpeiza de datos

In [1]:
#Librerias a usar
import pandas as pd
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Lectura
ruta = "../data/raw/housing.csv"
data = pd.read_csv(ruta)

In [4]:
#Caracteristicas generales
from IPython.display import display

print(data.shape)
display(data.head())

(20640, 10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [5]:
# ver las variables categoricas y las numericas
display(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

None

### Limpieza de datos

In [6]:
#Datos faltantes
valores_faltantes = data.isnull().sum().sort_values(ascending= False)
print("Valores faltantes ordenados: ")
display(valores_faltantes.to_frame('Cantidad de valores faltantes'))

#Elementos duplicados
print(f"\nElementos duplicados: {data.duplicated().sum()}")

Valores faltantes ordenados:

                    Cantidad de valores faltantes
total_bedrooms                                207
longitude                                       0
latitude                                        0
housing_median_age                              0
total_rooms                                     0
population                                      0
households                                      0
median_income                                   0
median_house_value                              0
ocean_proximity                                 0

Elementos duplicados: 0